# https://taskfile.dev

version: '3'

vars:
  PROJECT: termos
  APP: termos
  SRCDIR: src/

tasks:
  default:
    dir: $WORKDIR
    desc: run app
    cmds:
      - direnv exec . mamba run -n {{.PROJECT}} python -m {{.PROJECT}} {{.CLI_ARGS}}
    silent: true

  logs:
    desc: logs
    cmds:
      - tail -f ~/Library/Logs/net.cacko.termoservice/termosvc.log 

  export:
    desc: export env
    cmds:
      - direnv exec . mamba env export --no-builds -n {{.PROJECT}} > environment.yml

  start:
    desc: start
    cmds:
      - sudo launchctl start net.cacko.termoservice

  stop:
    desc: stop
    cmds:
      - sudo launchctl stop net.cacko.termoservice


  restart:
    desc: stop
    cmds:
      - sudo launchctl stop net.cacko.termoservice
      - sleep 10
      - sudo launchctl start net.cacko.termoservice

  push:
    desc: commit and pushes current changes
    cmds:
      - git add .  || true
      - gcom || true
      - git push || true

  pull:
    desc: pulls from git
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;cd /var/www/{{.PROJECT}};git reset --hard;git pull'

  pp:
    desc: push and pull
    cmds:
      - task: push
      - task: pull

  run:
    desc: run
    dir: $WORKDIR
    cmds:
      - mamba run -n {{.PROJECT}} python {{.ENTRY}}

  build:
    desc: build app
    cmds:
      - rm -rf {{.APP}}.build
      - rm -rf {{.APP}}.dist
      - mamba run -n {{.PROJECT}} python -m nuitka {{.ENTRY}}