# https://taskfile.dev

version: '3'

vars:
  PROJECT: termos
  APP: termos

tasks:
  default:
    dir: src
    desc: run app
    cmds:
      - direnv exec . mamba run -n {{.PROJECT}} python -m {{.PROJECT}}.cli {{.CLI_ARGS}}
    silent: true

  logs:
    desc: monitor logs
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;journalctl --user-unit {{.PROJECT}} -f --all'

  export:
    desc: export env
    cmds:
      - direnv exec . mamba env export --no-builds -n {{.PROJECT}} > environment.yml

  start:
    desc: start
    cmds:
      - sudo launchctl start net.cacko.termoservice

  stop:
    desc: stop
    cmds:
      - sudo launchctl stop net.cacko.termoservice


  restart:
    desc: stop
    cmds:
      - sudo launchctl stop net.cacko.termoservice
      - sleep 10
      - sudo launchctl start net.cacko.termoservice

  push:
    desc: commit and pushes current changes
    cmds:
      - git add .  || true
      - git commit -am "$(curl -s https://commit.cacko.net/index.txt)" || true
      - git push || true

  pull:
    desc: pulls from git
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;cd /var/www/{{.PROJECT}};git reset --hard;git pull'

  pp:
    desc: push and pull
    cmds:
      - task: push
      - task: pull

  exec:
    desc: run  cli on remote
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;cd /var/www/{{.PROJECT}}/src;mamba run -n {{.PROJECT}} python -m {{.PROJECT}}.cli {{.CLI_ARGS}}'

  start:
    desc: start the service
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;systemctl --user start {{.PROJECT}}'

  stop:
    desc: stop the server
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;systemctl --user stop {{.PROJECT}}'

  restart:
    desc: restart the service
    cmds:
      - task: stop
      - ssh $REMOTE_HOST 'source ~/.zshrc;sleep 1'
      - task: start

  deploy:
    desc: shortcut for stop -> push -> pull -> restart
    cmds:
      - task: stop
      - task: push
      - task: pull
      - task: restart

  run:
    desc: systemd exec
    dir: src/
    cmds:
      - bluetoothctl power on
      - direnv exec . mamba run -n {{.PROJECT}} python -m {{.PROJECT}}
  