lametric:
  headers:
    x-device: 64.2.A.2.103
  base_url: http://192.168.0.105:32321/api/
  endpoints:
    nowdata: termo
firebase:
  admin_json: /Volumes/Devo/Code/termo-4737a-firebase-adminsdk-9nxg7-2c9a5f303e.json
  rdb_host: https://termo-4737a-default-rtdb.europe-west1.firebasedatabase.app/
db:
  url: postgres://jago@192.168.0.10:5432/termo
devices:
  -
    mac: "44532"
    address: 192.168.0.106
    sensor_type: http
    location: indoor
    uuid_read: /api/now
  -
    mac: 50:4a:00:00:12:f3
    address: 58F19AD0-673B-9EB5-FD85-05084DBFF00F
    uuid_write: 0000fff5-0000-1000-8000-00805F9B34FB
    uuid_read: 0000fff3-0000-1000-8000-00805F9B34FB
    sensor_type: oria
    location: outdoor
  -
    mac: 50:7e:00:00:06:1c
    address: 69733674-301D-62BA-1C48-F4CCAD3F769C
    uuid_write: 0000fff5-0000-1000-8000-00805F9B34FB
    uuid_read: 0000fff3-0000-1000-8000-00805F9B34FB
    sensor_type: oria
    location: indoor